/**
 * Multilingual bio. Five languages sharing the same structure so the
 * toggle can swap them without layout shift. Each record carries a
 * native-script label (for the selector) plus the paragraphs that
 * make up the essay.
 *
 * Content: who I am → three questions driving the work → hardware
 * depth → theory as foundation → the philosophical question →
 * direction. Edit freely.
 */

export const BIO_LOCALES = ["en", "ko", "ja", "de", "zh"] as const;
export type BioLocale = (typeof BIO_LOCALES)[number];

export type BioContent = {
  /** Label shown in the language selector, in native script */
  label: string;
  /** BCP-47 language tag for the `lang` attribute */
  langTag: string;
  /** Page-level heading shown above the paragraphs */
  heading: string;
  /** Body paragraphs */
  paragraphs: string[];
};

export const BIO: Record<BioLocale, BioContent> = {
  en: {
    label: "English",
    langTag: "en",
    heading: "About me",
    paragraphs: [
      "I'm Jaehong Oh — a robotics software engineer and research intern on the ROBOTIS Perception Team, studying Mechanical Engineering at Soongsil University in Seoul. My work lives at the intersection of hardware constraints and the kind of structural questions that engineering alone cannot resolve. Most people who build robots think primarily about what systems can do. I spend at least as much time thinking about what they can know — about their own state, their environment, the relationship between a model and the thing it models. That asymmetry is not incidental. It shapes every architectural decision I make, from sensor validation protocols to the formal structure of the learning objective, from control frequencies to how I define system failure. The question came before engineering. Before writing a single line of ROS code, before commissioning a motor controller, I spent years with a different kind of problem in a different medium — the kind of sustained attention where you cannot defer to a compiler or a test suite, where the only available verification is whether what you wrote actually says what you think it says. The question that kept surfacing, in many different forms: what persists when something cannot fully observe itself? What remains coherent when no observer has complete access? I have not answered it. But it has organized almost everything I have built since, because the hardware version of that question appears at every layer of every system I have integrated — and the engineering answers, taken alone, never quite close it. What I have found is that the question keeps changing notation without changing substance. It arrived as a problem in one medium. It became a representational problem. It became a topological problem. That sequence is not coincidence — it is what happens when you refuse to settle for a formulation that is only partly right. The topological framing is the most precise one I have found, and it is the framing behind both SCC and ONN: the soft cohesion field is what persists when no observer has complete access, and its gauge invariance is what makes the question well-posed rather than just philosophically interesting.",

      "Three projects track the progression of the work, each sharpening the same underlying question in a different way. TurtleBot4 is an industrial safety monitoring system for factory environments, built with a seven-person team. The detection pipeline runs YOLOv8n for simultaneous human and PPE classification; above it sits a 4D Kalman filter tracking position, velocity, acceleration, and jerk — the jerk term is non-standard but necessary to maintain consistent identity during the partial-visibility intervals that factory floor clutter creates. The filter achieves 24.7% noise reduction over raw detector output. Navigation runs on ROS2 Nav2; multi-robot coordination flows through an MQTT broker with a central cloud relay. System metrics: 92.3% detection accuracy, 350ms end-to-end response time from camera input to alert, 96% autonomous navigation success across the full fleet. Soma Cube is reinforcement learning for robotic assembly on a Doosan M0609 manipulator with an OnRobot RG2 gripper. The sensing stack includes Whisper for speech command recognition and YOLOv8 on an RGB-D stream for three-dimensional scene understanding. The core learning algorithm is a Masked DQN with legal-action masking: the policy mask prevents illegal moves before the Q-function evaluates them, accelerating convergence and preventing unsafe configurations structurally rather than through reward penalties. Recovery is handled by Safe ZYZ Regrasp, which re-orientates the grasp when the current configuration is geometrically invalid. Motion planning runs through MoveIt2. Training ran for 105,300 episodes, converging from a 54% baseline to 96.1% overall assembly success with 93.7% illegal grasp prevention. The key structural insight was that collision avoidance cannot be a reward penalty after the fact — it has to be built into the action space itself. ONN is a topology-preserving network where the latent state carries explicit ontological structure rather than leaving it implicitly encoded in weights. The loss functional has three components: L_consensus for inter-node agreement, L_ricci for Forman-Ricci curvature preservation, and L_homology for persistent homology distance across topological features. Topology preservation rate is 99.75% across 3 million relational nodes; perplexity improvement over Transformer baselines is 14.7%; arXiv preprint 2506.19277. Each project sharpened the same question: what structure needs to be preserved for a system to keep working after the demo ends?",

      "The deepest hardware work is the Frontier mobile manipulator at ROBOTIS — a system I helped integrate from the ground up over the course of my internship. Frontier runs 16 joints across three kinematic chains, coordinated by four independent Controller Managers running in separate ROS2 namespaces. The Base CM (20Hz) handles the AntBot four-wheel swerve drive through a serial bridge on /dev/antbot_rcu, translating ROS2 hardware interface commands to the RCU protocol. The Arm CM (100Hz) drives the six-DOF OMY F3M Dynamixel chain through a U2D2 adapter on /dev/u2d2_f3m; the 100Hz rate required empirical validation before the architecture was committed — I measured p99 SyncRead latency at 4Mbps across all six axes simultaneously to verify the timing was achievable before locking in the control frequency. The Head CM (20Hz) handles the pan-tilt unit through /dev/u2d2_head. The Leader CM (100Hz) drives the OMY-L100 teleoperation interface on /dev/u2d2_l100, with an additional leader_arm_bridge node that maps leader joint angles to follower joint commands in real time. The URDF architecture uses partial compilation with sub-RSPs and a joint-state merger: each kinematic chain publishes its own joint states through its own RSP, the root RSP owns the TF tree and ingests the merged joint-state topic produced by the joint-state merger. This isolation ensures that no chain's failure takes down another chain's transforms, and the root TF tree remains coherent even when individual chains are partially initialized — the design is what made the four-camera bringup tractable. The four cameras — two RealSense D435i units, one D405, and one ZED Mini — are validated not by mean FPS but by inter-frame tail latency and burst-drop patterns under simultaneous load. Mean FPS hides the failure mode that actually breaks dataset collection: occasional inter-frame intervals three to five times the nominal period, which introduce motion blur and temporal inconsistency invisible in summary statistics but devastating to dataset quality. The antbot_navigation package — contributed to the ROBOTIS open-source AntBot repository — provides Nav2 navigation with saved-map, SLAM, and localization-only modes. RPP planner for real hardware, MPPI for Gazebo simulation, both inside a single package that branches on the mode launch argument (mode:=real, mode:=sim, mode:=localization).",

      "The theoretical frameworks — Soft Cognitive Cohesion (SCC) and Ontology Neural Networks (ONN) — grew from the engineering rather than running parallel to it. Each major hardware problem I encountered pointed toward a formal gap that the engineering vocabulary alone could not fill. SCC is the formal attempt to fill the foundational one. SCC formalizes a pre-objective formation theory. The primitive entity is not an object but a soft cohesion field u_t : X_t → [0,1] defined over a relational support space X_t. Objects are derived entities: they emerge as gauge-invariant topological invariants of the relational structure rather than being assumed as primitive. Existence is derived, not postulated — and that distinction matters formally. The four energy terms governing the field's dynamics — closure, separation, boundary, and transport — are conceptually independent; collapsing them would destroy the structural distinctions the theory is designed to track. Closure carries stabilization tendency under axiom A3: the field is driven toward a stable configuration, but not necessarily an idempotent one. Idempotence is a stronger claim than the theory supports, and the difference matters for what kinds of hardware behavior the theory can explain and predict. ONN takes this scaffolding into the learning regime. The latent state carries explicit ontological structure, encoding relational topology rather than leaving it implicit in the weight geometry. The ORTSF operator family closes the feedback loop on top of this topology with delay-robust control — the operators remain well-defined under the bounded delays that real sensor and actuator channels introduce. Topology preservation rate over 3 million relational nodes is 99.75%; perplexity improvement over Transformer is 14.7%. The framework paper was accepted at the International Journal of Topology in 2026. What keeps both frameworks from being purely academic exercises is a pattern I keep encountering in hardware: when a system fails in a way that standard diagnostics cannot explain, the missing ingredient is almost never more data. It is missing structure. Getting that structure right does not make systems better in the sense of tuning a metric. It makes them fail in ways that are diagnosable rather than opaque — and that shift, from opaque failure to diagnosable failure, is what enables meaningful engineering progress.",

      "There is a question I have been working with for years — well before I started writing code, and in a medium that has no compile step, no test suite, no benchmark. The question concerns what a system preserves when it cannot observe itself completely. Every self-referential system reaches a boundary where its model of itself is necessarily incomplete — not because of insufficient data, but because of the structural relationship between observer and observed. The observer always omits something in the act of observation. The question is whether that omission is a defect to close or a structural feature of any observer-observed system, and whether the thing that persists despite the omission is meaningful and formalizable. I came to this through sustained work in a medium that forces precision in a different way than engineering does. Engineering lets you defer to measurement — if a number comes out right, you can proceed. The medium I mean does not offer that exit. You have to keep revising until what you wrote says what you actually think, not what you half-think, not what you wish were true. It is the kind of work where the question keeps resisting clean formulation and you have to track why it resists rather than forcing it into a shape that fits. Working that way for long enough reveals when a question has genuinely changed form and when it has only changed notation. The question changed notation multiple times. It looked like a language problem. Then a representational problem. Then a topological problem. The topological framing turned out to be the most precise. In the topological framing, the gap between observer and observed maps onto the incompleteness of a system's self-model in a way that is well-posed: the cohesion field is what persists under incomplete observation, and its gauge invariance is what makes the persistence robust rather than contingent. The stabilization tendency in axiom A3 is not idempotence — it is a weaker claim, and the weakness is deliberate. The field approaches a stable configuration without necessarily reaching a fixed point, and that asymptotic behavior is closer to what actually happens in systems that navigate the observer/observed gap without resolving it. SCC is my formal attempt at an answer. What keeps it from being philosophical decoration is that it has direct engineering consequences — the kind that show up in sensor specifications, control frequencies, and planner design choices.",

      "The direction I am working toward runs on bidirectional arrows, and I have become convinced this is the only honest way to operate. Hardware failures are data about theory. An arm oscillating at a control boundary is not just an instability problem — it signals that the topology of the relevant state space has a feature the controller is not representing. The oscillation boundary is where the controller's model of the arm's configuration space breaks down, and the breakdown is specific: it points to a region of the relational geometry absent from the representation. A camera that loses synchronization under burst load is evidence that the system's timing structure makes an assumption about the inter-frame interval distribution that the actual hardware does not satisfy — and the p99 tail latency is the measurement that exposes where the assumption breaks, not the mean FPS. A grasp that fails in a configuration the policy never encountered is evidence that the policy's implicit model of the relational geometry of hand-object contact is incomplete in a specific, localized way — not globally wrong, but missing the topology of that subset. In the other direction, when the theory gets sharper, it generates specific hardware requirements. The stabilization tendency in A3 implies that the arm controller should not require convergence to a fixed point — it should allow continued motion tracking in states that are stable but not fixed, which is a different controller specification from one derived from idempotence. The Betti number preservation requirement in ONN implies that the sensor stack must reconstruct the topological structure of the scene, not just the geometric distances — depth sensors need to be validated by topological consistency metrics, not only point-cloud accuracy. These are not abstract design preferences. They are requirements that emerge from getting the theory right. My goal is to work at the place where those arrows are both active simultaneously — where hardware is generating theory data at the same rate that theory is generating hardware requirements. The architecture I am building toward makes ontological structure explicit at every layer: from raw sensor input, through learned latent representations that preserve relational topology, to the control interface that moves physical hardware. The problems worth solving are the ones where topology correctness is load-bearing — where getting it wrong breaks the system in a specific, diagnosable way, and getting it right enables a class of behavior that was not possible before.",
    ],
  },

  ko: {
    label: "한국어",
    langTag: "ko",
    heading: "자기소개",
    paragraphs: [
      "오재홍은 숭실대학교 기계공학과에 재학 중인 로보틱스 연구자로, 현재 ROBOTIS 퍼셉션 팀에서 연구 인턴으로 활동하고 있습니다. 그의 연구 관심사는 단순한 알고리즘 설계나 하드웨어 제어를 넘어, 보다 근본적인 질문인 시스템이 무엇을 알 수 있는가에 집중되어 있습니다. 이 질문은 공학적 필요에 의해 생겨난 것이 아니라, 그보다 훨씬 이전에 전혀 다른 방식의 지속적 작업을 통해 자연스럽게 형성되었습니다. 어떤 것이 자기 자신을 완전히 관찰하지 못할 때 무엇이 보존되는가, 그리고 관찰자와 관찰 대상 사이의 간극은 어떻게 정의될 수 있는가 하는 철학적 물음이 그 출발점이었습니다. 이 물음은 처음에는 언어적 형태를 띠었으나, 시간이 지남에 따라 구조적 사유로, 그리고 마침내 위상학적 형식으로 변화해 나갔습니다. 오재홍은 기계공학이라는 실증적 훈련과 이러한 추상적 질문 사이의 긴장을 생산적으로 유지하면서, 이론과 실험 양쪽에서 연구를 진행하고 있습니다. 그의 작업은 인식론적 질문을 공학 시스템의 설계 원칙으로 전환하려는 시도이며, 이는 그가 참여한 모든 프로젝트에 일관되게 흐르는 근본 동기입니다. 기계공학이라는 훈련은 도구를 제공하지만, 그가 실제로 탐구하는 것은 어느 층에서든 물리적 시스템이 자신의 상태와 환경에 대해 가질 수 있는 인식의 한계이며, 그 한계를 올바르게 설계하는 방법입니다.",

      "오재홍이 참여한 대표적인 로보틱스 프로젝트 중 하나는 7인으로 구성된 팀에서 수행한 TurtleBot4 기반 다중 로봇 탐색 및 제어 시스템입니다. 이 프로젝트에서는 YOLOv8n을 이용한 실시간 객체 탐지 파이프라인을 구축하였으며, 탐지 정확도는 92.3%를 달성하였습니다. 특히 주목할 만한 기술적 기여는 4D 칼만 필터의 설계로, 위치·속도·가속도·저크를 포함한 4차원 상태 벡터를 추정함으로써 기존 대비 24.7%의 노이즈 감소를 실현하였습니다. 시스템의 응답 속도는 350ms로 유지되었으며, 제어 성공률은 96%에 달하였습니다. 다중 로봇 간 통신은 MQTT 중앙 클라우드 브로커를 통해 구성되었으며, Nav2 스택을 활용하여 경로 계획 및 자율 주행 기능을 통합하였습니다. 두 번째 프로젝트는 소마큐브 조립으로, Doosan M0609 협동로봇과 OnRobot RG2 그리퍼를 기반으로 하며 Whisper STT 및 YOLOv8 RGB-D 인식을 결합하였습니다. 강화학습 알고리즘으로는 합법행동마스킹 기반 Masked DQN을 적용하여 불법 파지 동작을 사전에 차단하였고, Safe ZYZ Regrasp 전략과 MoveIt2 동작 계획을 결합해 105,300 에피소드 훈련 끝에 54% 베이스라인에서 96.1% 성공률로 수렴하였으며 불법 파지 방지율은 93.7%에 달하였습니다. 세 번째는 ONN으로, L_consensus, L_ricci(Forman-Ricci 곡률), L_homology(영속 호몰로지)를 결합한 손실 함수로 300만 노드에서 99.75% 위상 보존율, 트랜스포머 대비 퍼플렉시티 14.7% 향상을 달성하였습니다. arXiv 프리프린트는 2506.19277입니다. 각 프로젝트는 같은 질문을 더 날카롭게 만들었습니다. 데모가 끝난 뒤에도 시스템이 작동하려면 어떤 구조가 보존되어야 하는가.",

      "오재홍이 ROBOTIS에서 참여하고 있는 Frontier 로봇 플랫폼 작업은 하드웨어와 소프트웨어 통합의 복잡성을 정면으로 다루는 작업입니다. Frontier는 16개의 관절과 3개의 운동학적 체인으로 구성된 이동 조작 로봇으로, 4개의 독립적인 Controller Manager를 통해 각 서브시스템이 분리 관리됩니다. Base CM은 20Hz로 /dev/antbot_rcu를 통해 AntBot 스워브 구동계를 제어하고, Arm CM은 100Hz로 /dev/u2d2_f3m을 통해 6-DOF OMY F3M Dynamixel 암을 구동하며, Head CM은 20Hz로 /dev/u2d2_head를 통해 팬틸트 헤드를 제어합니다. Leader CM은 100Hz로 /dev/u2d2_l100과 leader_arm_bridge를 통해 리더-팔로워 조작 인터페이스를 지원합니다. URDF 구조는 부분 정의와 서브 RSP, 조인트 상태 병합기를 포함하며, 루트 RSP가 전체 TF 트리를 소유합니다. 4Mbps 통신 대역에서 6축 동시 SyncRead의 p99 레이턴시를 실측하여 100Hz 동작을 검증하였으며, 아키텍처를 확정하기 전에 이 측정을 통해 타이밍 달성 가능성을 확인하였습니다. 카메라 시스템은 2×D435i, D405, ZED Mini로 구성되어 있고, 평균 FPS가 아닌 프레임 간 테일 레이턴시와 버스트 드롭 패턴 분석을 통해 성능을 검증하였습니다. 평균 FPS는 실제 데이터셋 수집을 망가뜨리는 프레임 간격 이상을 숨기기 때문입니다. antbot_navigation 패키지에도 기여하여 RPP(실제 환경)와 MPPI(시뮬레이션)를 mode:=real/sim/localization 파라미터로 전환 가능하도록 구현하였으며, 저장 지도 주행, SLAM, 로컬라이제이션 전용 모드를 지원하는 이 코드는 ROBOTIS 오픈소스로 공개되었습니다.",

      "오재홍은 온톨로지 신경망(ONN) 연구에도 깊이 참여하고 있으며, 이 연구는 arXiv 2506.19277로 공개된 바 있고 Int. J. Topol. 2026에 게재 승인을 받았습니다. ONN은 잠재 상태 공간에 명시적인 온톨로지 구조를 도입함으로써, 기존 트랜스포머 아키텍처가 암묵적으로 가정하는 구조적 중립성에서 벗어나고자 합니다. 핵심 손실 함수는 세 가지 항으로 구성되어 있습니다. L_consensus는 합의 기반 일관성을 강제하며, L_ricci는 Forman-Ricci 곡률을 활용하여 그래프의 국소 곡률 구조를 학습에 반영합니다. L_homology는 영속 호몰로지를 통해 전역 위상적 특징을 보존합니다. 이 구조 덕분에 300만 노드 규모의 그래프에서 99.75%의 위상 보존율을 달성하였으며, 트랜스포머 대비 퍼플렉시티가 14.7% 향상되는 성과를 거두었습니다. ORTSF 연산자군은 지연에 강건한 피드백 구조를 제공하며, 이는 실시간 로봇 시스템에서 발생하는 타이밍 불확실성을 이론적으로 수용하기 위한 설계입니다. 이 연구의 기반이 되는 SCC 이론에서, 원시 개체는 관계 지지 공간 위에 정의된 soft cohesion field u_t : X_t → [0,1]이며, 존재는 게이지 불변 위상 불변량으로서 가정이 아닌 도출을 통해 나타납니다. 에너지 4항(폐합, 분리, 경계, 수송)은 개념적으로 독립적이고, 폐합 항은 공리 A3 하에서 안정화 경향을 가집니다. 이것은 멱등성과 다릅니다. 시스템이 안정 구성으로 수렴하되 고정점을 반드시 가질 필요는 없다는 이 구분은, 암 컨트롤러 설계에 직접적인 실천적 함의를 가집니다. 기존 진단 도구로 설명되지 않는 시스템 오작동 앞에서, 오재홍이 반복해서 발견한 것은 부족한 것이 데이터가 아니라 구조라는 사실입니다.",

      "오재홍의 연구 전체를 관통하는 가장 중요한 구조는 하드웨어 경험과 이론 사이의 양방향 화살표입니다. 한 방향에서는 하드웨어의 실패가 이론을 위한 데이터가 됩니다. Frontier 암의 제어 경계에서 발생하는 진동 현상은 그 자체로 위상 구조의 부재를 드러내는 신호였으며, 카메라의 버스트 동기 손실은 시스템이 암묵적으로 가정하던 타이밍 조건의 위반을 가시화하였습니다. 소마큐브 작업에서 미경험 구성에 대한 파지 실패는 학습된 표현의 관계 기하학이 불완전함을 의미하는 것으로 해석되었습니다. 반대 방향에서는 이론의 심화가 하드웨어 설계 결정을 이끌었습니다. SCC 이론에서 폐합 항이 공리 A3 하의 안정화 경향(멱등성이 아님)을 가진다는 사실은, 암 컨트롤러가 반드시 고정점으로의 수렴을 강제할 필요가 없음을 시사하였습니다. ONN에서 Betti 수 보존이 달성된다면, 센서의 깊이 정보는 기하학적 거리만이 아닌 위상 구조 전체를 재구성하기 위한 충분 조건이 될 수 있습니다. SCC의 응집장은 관찰자와 관찰 대상 사이의 간극이라는 철학적 질문에 대한 형식적 응답입니다. 존재는 게이지 불변이고 위상 불변인 양으로 도출되며, 이는 가정이 아닌 결과입니다. 오재홍에게 로보틱스 연구란 결국 시스템이 자기 자신을 완전히 알 수 없는 조건 속에서도 무엇이 보존되고 무엇이 작동하는가를 묻는 방식이며, 그 물음은 지금도 계속 진행 중입니다. 지향하는 것은 온톨로지 구조가 모든 층에서 명시적으로 유지되는 인지-추론 아키텍처입니다. 원시 센서 입력에서, 관계 위상을 보존하는 학습된 잠재 표현을 거쳐, 물리적 하드웨어를 움직이는 제어 인터페이스까지.",

      "오재홍이 나아가는 방향에서, 해결할 가치가 있는 문제들은 위상을 올바르게 잡는 것이 실제로 더 나은 공학적 결정을 강제하는 동시에, 하드웨어가 이론의 빈 곳을 드러내는 교차점에 자리하고 있습니다. 그는 이것이 정직하게 작업하는 유일한 방식이라고 생각하게 됐습니다. 코드를 쓰기 훨씬 전부터 붙들고 있던 질문이 있습니다. 어떤 것이 자기 자신을 완전히 관찰할 수 없을 때 무엇이 보존되는가. 관찰자와 관찰 대상 사이의 간극, 그리고 그 간극이 메워야 할 결함인지 제거할 수 없는 구조적 특성인지. 그 질문에는 다른 매체를 통해 다가갔습니다. 자신이 실제로 무엇을 생각하는지를 정확히 표현하도록 강제하는 종류의 작업을 통해서입니다. 질문은 계속 형태를 바꿨습니다. 언어의 문제처럼 보였다가, 구조의 문제가 됐다가, 위상의 문제가 됐습니다. 결국 내린 결론은 이것들이 모두 다른 표기법으로 쓰인 같은 질문이라는 것입니다. SCC는 그 질문에 대한 형식적 시도입니다. 응집 장은 자기인식이 불완전할 때 지속되는 것이며, 어떤 관찰자도 완전한 접근권을 갖지 못할 때에도 살아남는 불변량입니다. 이것이 철학적 장식에 그치지 않는 이유는 직접적인 공학적 귀결이 있기 때문입니다. 안정화 경향은 암 컨트롤러 설계에, Betti 수 보존은 센서 검증 방법론에 직접 영향을 줍니다. 모든 층에서 온톨로지 구조가 명시적으로 유지되는 아키텍처를 향해, 두 방향의 화살표가 동시에 흐르는 연구 환경 안에서 일하는 것이 목표입니다.",
    ],
  },

  ja: {
    label: "日本語",
    langTag: "ja",
    heading: "自己紹介",
    paragraphs: [
      "私はオ・ジェホンと申します。現在、ROBOTISパーセプションチームにて研究インターンとして勤務しており、崇実大学機械工学科に在籍しております。ロボティクスの研究に取り組む中で私が常に根底に置いている問いは、システムは何を知ることができるか、という一点に集約されます。この問いは、エンジニアリングの訓練を通じて生まれたものではなく、それ以前に、ある種の持続的かつ集中的な営みの中で芽生えたものです。観察者と観察対象の間には埋めることのできない隙間が存在するのではないか、自己観察が不完全であるとき、いったい何が保存されるのか、という問いを私はその営みの中で繰り返し問い続けました。言語によって問いを立てれば立てるほど、問いそのものが言語の限界を超えて構造的な形式を求め始め、やがてトポロジカルな問いへと変化していくことに気づきました。その気づきがあったからこそ、私はエンジニアリングと数学的形式理論の両方を同時に追求する現在の研究スタイルへと自然に向かうことができたのだと考えております。ROBOTISという実装の場と、理論構築の場の双方において、この根本的な問いは今も私の研究を駆動し続けております。機械工学という訓練は道具を与えてくれますが、私が実際に探求しているのは、物理システムがあらゆる層で自身の状態と環境について持ちうる認識の限界であり、その限界を正しく設計する方法です。",

      "TurtleBot4を用いた自律移動ロボットシステムの開発では、7人チームのメンバーとして知覚・制御統合アーキテクチャの設計と実装を担当いたしました。物体検出にはYOLOv8nを採用し、検出精度92.3%を達成する一方、単純な検出にとどまらず状態推定の精度向上に注力いたしました。具体的には、位置・速度・加速度・ジャークの4次元状態量を同時推定する4Dカルマンフィルタを独自設計し、24.7%のノイズ低減を実現いたしました。高次微分量であるジャークまでを状態量に含めることで、センサノイズが累積しやすい動的環境においても安定した追跡が可能となりました。ナビゲーションスタックにはROS 2のNav2を用い、大域経路計画と局所回避行動を統合的に管理いたしました。また、MQTTプロトコルを介した中央クラウドブローカーによる分散制御アーキテクチャを構築し、複数ロボットの協調動作を350msという応答時間で実現いたしました。制御精度は96%に達し、実環境における安定した自律行動を確認いたしました。このシステム開発を通じて、知覚から制御に至るパイプライン全体を設計・評価するという実践的な経験を深く積むことができました。",

      "Doosan M0609マニピュレータとOnRobot RG2グリッパを用いたソマキューブ自動組立システムは、音声・視覚・操作を統合した複合知覚制御システムとして設計いたしました。音声認識にはOpenAIのWhisperを用いたSTTシステムを実装し、オペレータとのインタラクションを自然言語で実現いたしました。物体認識にはYOLOv8をRGB-D情報と組み合わせ、ピースの三次元位置と姿勢を高精度に推定いたしました。強化学習エージェントにはMasked DQNを採用し、合法行動マスキングによって93.7%の違法グラスプを防止することに成功いたしました。行動空間全体を探索させるのではなく、物理的・幾何学的制約に基づいて探索空間を事前に絞り込むというこの手法は、サンプル効率と安全性の両立という観点から非常に有効であることが実証されました。把持姿勢の再調整にはSafe ZYZリグラスプ戦略を実装し、MoveIt2との統合によって滑らかかつ安全な軌道計画を実現いたしました。105300エピソードの学習を経て、ベースライン54%から96.1%への成功率向上を達成いたしました。このプロジェクトは、知覚・推論・制御の三層を密結合させたシステム設計の実践的探求として、私の研究の重要な基盤となっております。衝突回避は事後的な報酬ペナルティとして扱うのではなく、行動空間そのものに組み込む必要があるという洞察が、このシステムの核心にあります。",

      "Frontierハードウェアプラットフォームの開発では、16関節・3運動連鎖から構成される複合ロボットシステムの制御アーキテクチャを構築いたしました。4つのController Managerを明確に分離した設計とし、ベースCMは20HzでAntBotスワーブモジュール(/dev/antbot_rcu)を担当、アームCMは100Hzで6-DOF OMY F3M Dynamixelアクチュエータ(/dev/u2d2_f3m)を制御、ヘッドCMは20Hzでパン・チルト機構(/dev/u2d2_head)を操作、リーダーCMは100Hzで/dev/u2d2_l100とleader_arm_bridgeを介したテレオペレーション入力を処理いたします。TFツリーの所有権はルートRSPが一元管理し、部分URDFとサブRSPおよび関節状態マージャーによって複雑なキネマティクスツリーを統一的に表現しております。4Mbpsの通信帯域において6軸同時SyncReadを実行し、p99レイテンシの実測によって100Hzの制御帯域が実際に保証されていることを検証いたしました。この検証はアーキテクチャを確定する前に実施し、タイミングの実現可能性を事前に確認いたしました。カメラシステムには2台のD435iとD405、さらにZED Miniを組み合わせており、評価指標として平均FPSではなくInter-frameテールレイテンシおよびバースト・ドロップパターンを用いることで、実使用条件における最悪ケース性能を正確に把握いたしました。antbot_navigationではRPP(実機モード)とMPPI(Gazeboシミュレーションモード)を切り替え可能とし、ROBOTISオープンソースエコシステムとの整合性を保ちつつ研究利用に適した拡張性を確保しております。mode:=real、mode:=sim、mode:=localizationの3モードを単一パッケージで実現しています。",

      "私の理論研究の中核にあるのは、ソフト凝集場(SCC)理論とオントロジーニューラルネットワーク(ONN)という二つの形式体系です。SCC理論では、ソフト凝集場 u_t: X_t → [0,1] を関係的支持空間上に定義し、存在をゲージ不変トポロジカル不変量として仮定するのではなく導出するという立場を取っております。エネルギー関数は閉合・分離・境界・輸送の4項から構成されており、これらは概念的に独立した項として設計されており、各項の寄与を個別に解析できる構造を持っております。閉合項は公理A3のもとで安定化傾向を示しますが、これはべき等性とは明確に区別されるものです。安定化傾向とは、フィールドが安定した構成に向かって駆動されるが、必ずしも固定点に収束するわけではないことを意味します。この区別は、ハードウェアの制御設計において直接的な実践的含意を持ちます。一方、ONN研究では、潜在状態に明示的なオントロジー構造を埋め込み、L_consensus・L_ricci(Forman-Ricci曲率)・L_homology(永続ホモロジー)の三つの損失項によってトポロジカル一貫性を制約として学習に組み込む手法を開発いたしました。300万ノードのグラフに対して99.75%のトポロジー保存率を達成し、Transformerベースラインに対してパープレキシティ14.7%の改善を確認いたしました。この成果はarXiv 2506.19277として公開されており、ORTSFオペレータ群による遅延ロバストフィードバック制御の理論とともにInt. J. Topol. 2026に採択されております。",

      "私がこれらの研究を通じて追求し続けているのは、冒頭に述べた問い、すなわち自己観察が不完全であるとき、何が保存されるか、という問いへの形式的な答えです。観察者と観察対象の隙間は、エンジニアリングシステムにおいても、数学的形式体系においても、同型の問題として現れます。問いはかつて言語の中にありましたが、やがて構造の問いへ、そしてトポロジーの問いへと変化いたしました。SCCの凝集場は、その変化の先に辿り着いた形式的な答えの一つです。そして興味深いことに、ハードウェアの失敗は理論のデータとなり、理論の精緻化はハードウェアの設計決定を導くという双方向の矢印が、実際の研究過程において繰り返し確認されております。Frontierプラットフォームの制御境界での振動は、状態空間のトポロジー構造が表現から欠落していることを示す信号でした。カメラのバースト動機損失は、システムが暗黙に仮定していたタイミング条件の違反でした。ソマキューブにおける未経験構成への把持失敗は、学習された関係幾何学の不完全さを示していました。逆方向も同様です。A3の安定化傾向は、アームコントローラが固定点への収束を必要としないことを示唆します。Betti数保存の要件は、センサが幾何学的距離だけでなく場面のトポロジー構造を再構築する必要があることを示します。ハードウェアと理論が相互に精緻化し合うこの循環の中で作業し続けることが、私の目指す研究スタイルです。",
    ],
  },

  de: {
    label: "Deutsch",
    langTag: "de",
    heading: "Über mich",
    paragraphs: [
      "Jaehong Oh ist Forschungspraktikant im ROBOTIS-Perception-Team und studiert Maschinenbau an der Soongsil University in Seoul. Seine wissenschaftliche Laufbahn ist von Beginn an durch eine Frage geprägt, die weit über die klassische Ingenieurpraxis hinausgeht — nämlich die Frage, was Systeme überhaupt wissen können und wo die Grenze zwischen dem Beobachter und dem Beobachteten verläuft. Diese Frage entstand nicht innerhalb eines technischen Kontexts, sondern durch ein anderes Medium konzentrierter Arbeit, das ihn mit dem philosophischen Problem der Beobachter-Beobachtetes-Lücke konfrontierte: Was bleibt übrig, wenn Selbstbeobachtung strukturell unvollständig ist? Was kann ein System über sich selbst aussagen, wenn der Akt der Beobachtung selbst Teil des zu beschreibenden Systems ist? Diese fundamentale Spannung zwischen epistemischer Zugänglichkeit und ontologischer Vollständigkeit wurde zum Leitmotiv seines gesamten Forschungswegs. Jaehong Oh versteht Ingenieurarbeit nicht als bloße Anwendung bekannter Werkzeuge, sondern als einen Ort, an dem diese philosophischen Fragen konkrete, messbare Form annehmen — in Regelungsfehlern, in Sensorlatenzen, in Greiffehlschlägen und in topologischen Inkonsistenzen. Dieser Hintergrund macht ihn zu einem Forscher, der technische Probleme nicht isoliert betrachtet, sondern stets im Rahmen einer tieferen Frage nach der Wissensstruktur eingebetteter Systeme. Seine akademische Ausbildung im Maschinenbau liefert das formale Handwerkszeug, aber seine eigentliche Motivation liegt in der Untersuchung, ob und unter welchen Bedingungen ein physisches System ein kohärentes, konsistentes Modell seiner Umgebung aufbauen kann, das über bloße Signalverarbeitung hinausgeht und echte strukturelle Repräsentation leistet.",

      "Im Rahmen eines Sieben-Personen-Teams entwickelte Jaehong Oh ein umfassendes autonomes Navigationssystem auf Basis des TurtleBot4, das mehrere technische Herausforderungen simultan adressiert und dabei bemerkenswerte Leistungskennzahlen erreichte. Das System integriert YOLOv8n für Echtzeitobjekterkennung mit einer selbst entwickelten Zustandsschätzarchitektur — einem 4D-Kalman-Filter, das nicht nur Position und Geschwindigkeit, sondern auch Beschleunigung und Ruck als Zustandsgrößen verfolgt und dadurch eine Rauschreduktion von 24,7 Prozent gegenüber konventionellen Filtern erreicht. Diese Erweiterung des Zustandsraums erlaubt es dem System, dynamische Hindernisse mit deutlich höherer Vorhersagequalität zu verfolgen, was besonders in dichten oder sich schnell verändernden Umgebungen entscheidend ist. Die Navigationsplanung basiert auf dem Nav2-Stack, der in eine MQTT-basierte Kommunikationsarchitektur mit zentralem Cloud-Broker eingebettet wurde, sodass verteilte Steuerung und Fernüberwachung möglich sind. Die Erkennungsgenauigkeit des Gesamtsystems liegt bei 92,3 Prozent, die mittlere Antwortzeit des Regelkreises bei 350 Millisekunden, und der Regelungserfolg beträgt 96 Prozent. Für die Soma-Cube-Aufgabe dient ein Doosan M0609 mit OnRobot RG2 Greifer; Whisper STT und YOLOv8 RGB-D werden für Sprachbefehle und Szenenverständnis kombiniert. Ein Masked-DQN-Agent mit legalem Aktions-Masking verhindert 93,7 Prozent aller potenziell illegalen Griffe; Safe-ZYZ-Regrasp und MoveIt2 ergänzen die Manipulationspipeline. Nach 105.300 Trainingsepisoden stieg die Erfolgsquote von einer Baseline von 54 Prozent auf 96,1 Prozent. ONN ergänzt diese Projekte als topologieerhaltendes Netzwerk mit L_consensus-, L_ricci- und L_homology-Verlustterm: 99,75 Prozent Topologieerhaltung über 3 Millionen Knoten, 14,7 Prozent Perplexitätsverbesserung gegenüber Transformer-Baselines, arXiv-Preprint 2506.19277.",

      "Die Arbeit am Frontier-Roboter repräsentiert Jaehong Ohs tiefsten Einblick in die Herausforderungen der Hardware-nahen Systemintegration und der Echtzeitregelungsarchitektur für komplexe kinematische Strukturen. Der Frontier verfügt über 16 Gelenke, verteilt auf 3 kinematische Ketten, und wird durch 4 unabhängige Controller Manager gesteuert, die jeweils unterschiedlichen zeitlichen und kommunikativen Anforderungen genügen müssen. Der Basis-Controller-Manager operiert bei 20 Hz über den Anschluss /dev/antbot_rcu und steuert den AntBot-Swerve-Antrieb; der Arm-Controller-Manager läuft bei 100 Hz über /dev/u2d2_f3m und koordiniert den 6-DOF OMY F3M Dynamixel-Arm; der Kopf-Controller-Manager bei 20 Hz über /dev/u2d2_head für die Pan-Tilt-Einheit; und der Leader-Controller-Manager bei 100 Hz über /dev/u2d2_l100 mit einem dedizierten leader_arm_bridge-Knoten für Leader-Follower-Betrieb. Die URDF-Struktur ist teilweise aufgelöst und nutzt Sub-RSPs, wobei der Root-RSP den gesamten TF-Baum besitzt und die Gelenkzustandsdaten aller Controller über einen Merger aggregiert werden. Für die Validierung der 100-Hz-Anforderung des Arm-Controllers wurde die p99-SyncRead-Latenz bei 4 Mbps über alle 6 Achsen gemessen — ein Vorgehen, das statistische Ausreißer sichtbar macht, die bei ausschließlicher Betrachtung mittlerer Latenzwerte unsichtbar bleiben würden. Die Sensorkonfiguration umfasst zwei Intel D435i, eine D405 und eine ZED Mini, deren Synchronisationsverhalten Jaehong Oh nicht über mittlere FPS-Werte, sondern über Inter-Frame-Tail-Latenz und Burst-Drop-Muster charakterisiert. Die Navigation verwendet RPP im realen Betrieb und MPPI in der Gazebo-Simulation, umschaltbar über den Parameter mode:=real/sim/localization, und ist als ROBOTIS Open-Source-Beitrag veröffentlicht.",

      "Die theoretischen Forschungsarbeiten von Jaehong Oh umfassen zwei eng miteinander verbundene Rahmenwerke. Die Soft Cognitive Cohesion-Theorie definiert als primitives Objekt ein weiches Kohäsionsfeld u_t: X_t → [0,1] über einem relationalen Trägerraum und leitet Existenz als eichinvariante topologische Invariante ab, anstatt sie zu postulieren. Diese formale Entscheidung ist konzeptionell tiefgreifend: Existenz ist in SCC nicht gegeben, sondern emergiert aus der Kohäsionsstruktur des Feldes. Vier Energieterme — Abschluss, Trennung, Grenze und Transport — sind in der Theorie konzeptionell unabhängig gehalten; diese Unabhängigkeit ist eine bewusste ontologische Entscheidung. Der Abschlussterm unterliegt Axiom A3, das eine Stabilisierungstendenz beschreibt — explizit keine Idempotenz, da idempotente Abschlussoperatoren eine Fixpunktannahme voraussetzen, die in SCC nicht gilt und die für das Erklären bestimmter Hardwareverhalten entscheidend ist. Das Ontology Neural Network überführt diese Strukturprinzipien in eine lernfähige Architektur: Der latente Zustand trägt explizite ontologische Struktur, die Verlustfunktion kombiniert L_consensus mit L_ricci — basierend auf der Forman-Ricci-Krümmung — und L_homology, das persistente Homologie als Regularisierungssignal nutzt. An einem Graphen mit 3 Millionen Knoten wurde eine Topologieerhaltungsrate von 99,75 Prozent gemessen; gegenüber einem Transformer-Baseline wurde eine Perplexitätsverbesserung von 14,7 Prozent erzielt. Die Arbeit zur ORTSF-Operatorfamilie, die verzögerungsrobustes Feedback in dynamischen Systemen realisiert, wurde im International Journal of Topology 2026 angenommen; die arXiv-Vorabveröffentlichung ist unter der Kennung 2506.19277 zugänglich. Was beide Rahmenwerke von rein akademischen Übungen unterscheidet, ist ein Muster, das Jaehong Oh immer wieder in der Hardware antrifft: Wenn ein System auf eine Weise versagt, die konventionelle Diagnosetools nicht erklären können, ist das fehlende Element fast nie mehr Daten — es ist fehlende Struktur.",

      "Die philosophische Frage, die Jaehong Ohs Forschung antreibt, entwickelte sich im Laufe der Zeit durch eine charakteristische Verschiebung der Notation — von sprachlicher Formulierung über strukturelle Beschreibung bis hin zu topologischer Formalisierung. Diese Verschiebung ist kein bloß formales Phänomen, sondern ein Ausdruck davon, dass die Frage nach der Beobachter-Beobachtetes-Lücke in unterschiedlichen Beschreibungsräumen unterschiedlich scharf gestellt werden kann. Er ist zu dieser Frage durch ein anderes Medium gekommen — durch eine Art konzentrierter Aufmerksamkeit, die einen zwingt zu artikulieren, was man tatsächlich denkt, statt was man zu denken verpflichtet ist. Die Frage wechselte die Form wiederholt: Sie sah aus wie ein Sprachproblem, dann ein Strukturproblem, dann ein topologisches Problem. Was er schließlich zu erkennen begann, ist, dass es immer dieselbe Frage in verschiedener Notation ist. SCCs Kohäsionsfeld ist in diesem Sinne eine formale Antwort: Es beschreibt, wie Kohärenz entsteht, bevor diskrete Objekte identifiziert werden, und adressiert damit genau jenen Bereich, der bei unvollständiger Selbstbeobachtung unzugänglich bleibt. Die Stabilisierungstendenz unter Axiom A3 ist explizit keine Idempotenz — der Unterschied zwischen dem Anstreben einer stabilen Konfiguration und dem Erreichen eines Fixpunkts ist formal präzise und hat direkte Konsequenzen für die Regelungsarchitektur. SCC ist sein formaler Versuch einer Antwort. Was das zu mehr als philosophischem Beiwerk macht, sind die direkten ingenieurtechnischen Folgerungen, die in Sensorspezifikationen, Regelfrequenzen und Planerauswahl sichtbar werden.",

      "Die bidirektionalen Pfeile zwischen Theorie und Hardware sind keine Metapher, sondern konkret erfahrbare Wechselwirkungen. Arm-Oszillationen an der Regelungsgrenze des Frontier verweisen auf eine fehlende topologische Charakterisierung des Zustandsraums — der Regler sucht einen Fixpunkt, den die Geometrie nicht hergibt. Kamera-Synchronverluste unter Burst-Bedingungen zeigen, dass die dem System implizit zugrunde liegende Timing-Annahme verletzt ist — eine Beobachtung, die erst durch die Messung von Inter-Frame-Tail-Latenzen anstelle mittlerer FPS-Werte sichtbar wird. Greiffehlschläge in unbekannten Konfigurationen beim Soma-Cube-Projekt verweisen darauf, dass die relationale Geometrie des Greifraums unvollständig modelliert ist. In der Gegenrichtung liefert die Theorie operative Konsequenzen: Die Stabilisierungstendenz unter Axiom A3 impliziert, dass ein Arm-Controller keinen globalen Fixpunkt benötigt — lokale Kohärenz reicht aus, und das ist eine wesentlich andere Controllerauslegung als eine, die aus Idempotenz abgeleitet wird. Die Erhaltung von Betti-Zahlen durch den ONN-Lernprozess impliziert, dass ein Sensor die topologische Szenenstruktur rekonstruieren muss, nicht nur lokale Geometrie extrahieren — Tiefensensoren müssen daher mit topologischen Konsistenzmetriken validiert werden, nicht nur mit Punktwolkentreue. Jaehong Oh arbeitet genau in diesem Zwischenraum — zwischen dem formalen Apparat der Topologie und dem konkreten Versagen physischer Systeme — und versteht beide Seiten als Evidenz für dieselbe zugrundeliegende Frage. Sein Ziel ist eine kognitive Schlussfolgerungsarchitektur, bei der ontologische Struktur auf jeder Ebene explizit erhalten bleibt: vom rohen Sensoreingang über gelernte latente Repräsentationen, die die relationale Topologie bewahren, bis zur Regelungsschnittstelle, die physische Hardware bewegt.",
    ],
  },

  zh: {
    label: "中文",
    langTag: "zh-Hans",
    heading: "关于我",
    paragraphs: [
      "吴在洪是一位就读于首尔崇实大学机械工程系的机器人工程师，目前担任ROBOTIS感知团队研究实习生。他的研究轨迹从硬件系统延伸至数学理论，再延伸至哲学认识论，构成一条罕见的跨层次探索路径。在他正式踏入工程学领域之前，有一个问题以另一种媒介的形式先行到来：观察者与被观察对象之间究竟存在怎样的间隙？当自我观察本身不完整时，什么东西得以留存？这个问题最初并非以方程式或传感器数据的形式出现，而是以另一种专注工作的形式悄然浮现，随后逐渐从语言转化为结构，再从结构转化为拓扑，最终在他的软内聚场理论SCC中找到了形式化的回答。他深信，工程师对系统的认知能力边界，不仅是技术问题，更是本体论问题——系统究竟能知道什么，这个追问贯穿了他全部的研究工作，成为连接感知硬件、神经网络架构与数学理论的隐性主线。正因如此，他的研究风格兼具工程师的严谨与哲学家的执着，致力于在可测量的物理世界与不可还原的认识论结构之间寻找精确的对应关系。他的机械工程训练提供了运动学、控制理论和传感器融合的工具，但他真正探索的是物理系统在每个层面上对自身状态和环境所能拥有的认知边界，以及如何围绕这一边界进行正确的设计。",

      "在机器人系统集成领域，吴在洪参与并主导了多个技术密度极高的项目，其中TurtleBot4多机器人协同系统尤为突出。该项目由七人团队共同推进，核心任务是构建一套具备实时感知、分布式通信与自主导航能力的多机器人平台。在感知层，团队采用YOLOv8n作为目标检测骨干网络，实现了92.3%的检测精度；在状态估计层，吴在洪设计并实现了一套四维卡尔曼滤波器，同时对目标的位置、速度、加速度与加加速度进行联合估计，相较于传统方案噪声降低幅度达到24.7%，显著提升了轨迹预测的平滑性与鲁棒性。系统的通信架构采用MQTT协议构建中央云端代理，整体响应时间压缩至350毫秒以内，综合控制成功率达到96%。导航模块基于Nav2框架搭建。索玛立方体项目基于Doosan M0609机械臂和OnRobot RG2夹爪，结合Whisper语音识别与YOLOv8 RGB-D视觉理解，采用具有合法动作掩码的Masked DQN强化学习算法，将非法抓取预防率提升至93.7%，并通过Safe ZYZ重抓取策略与MoveIt2运动规划，历经105300回合训练，从54%基线提升至96.1%总体成功率。ONN作为拓扑保持网络，以L_consensus、L_ricci（Forman-Ricci曲率）和L_homology（持久同调）三项损失函数，在300万节点规模上实现了99.75%的拓扑保持率，相对Transformer基线困惑度提升14.7%，arXiv预印本编号2506.19277。每个项目都让同一个问题更加尖锐：演示结束后系统仍能运行，需要保存什么样的结构？",

      "吴在洪目前参与ROBOTIS Frontier机器人平台的开发工作，该平台具有16个关节、三条独立运动学链，整体控制架构由四个Controller Manager分层管理，技术复杂度极高。基座Controller Manager以20Hz频率运行，通过设备接口/dev/antbot_rcu驱动AntBot转向机构；机械臂Controller Manager以100Hz高频运行，通过/dev/u2d2_f3m接口控制6自由度OMY F3M Dynamixel舵机组；头部Controller Manager以20Hz运行，负责云台姿态控制；领导者Controller Manager同样以100Hz运行，通过/dev/u2d2_l100接口与leader_arm_bridge桥接模块协同工作，实现主从控制模式。在URDF与TF树管理方面，系统采用partial URDF加子机器人状态发布器的架构，通过关节状态合并器统一整合多链路状态，根RSP持有完整TF树的所有权。在通信性能验证方面，吴在洪在4Mbps带宽限制下完成了六轴同时SyncRead的p99延迟测量，在确定架构之前验证了100Hz控制频率的可达性。传感器阵列包括两台Intel D435i深度相机、一台D405近距相机与一台ZED Mini立体相机，他针对帧间尾部延迟与突发丢帧的非均匀模式进行了专项验证，明确区分了平均帧率与实际时序可靠性之间的差异，因为平均帧率会掩盖实际破坏数据集采集的故障。在导航贡献方面，他为antbot_navigation模块引入了RPP（真实机器人）与MPPI（Gazebo仿真）双规划器支持，并通过mode参数实现real/sim/localization三种部署模式的无缝切换，已贡献至ROBOTIS开源AntBot仓库。",

      "在理论研究层面，吴在洪构建了两套相互关联的数学框架，分别从不同角度回应「系统能知道什么」这一核心问题。其一是软内聚场理论SCC，其核心原语是定义在关系支撑空间上的软内聚场，表示为映射u_t从X_t到区间[0,1]，描述的是在离散对象化发生之前，认知形成的连续先驱结构。在SCC框架中，存在性被导出为规范不变拓扑不变量，而非作为公理假设引入，这一设计体现了深刻的本体论立场——存在不是给定的，而是从场的内在结构中涌现的。理论包含四个概念独立的能量项：闭合能、分离能、边界能与传输能，它们在数学上相互耦合，但概念上不可合并，任何简化都会破坏理论的解释力。闭合项在公理A3下具有稳定化倾向，这与幂等性有本质区别——稳定化意味着系统趋向于某种有界吸引域，而非精确收敛至固定点，这一区别对控制系统设计具有直接的实践含义。其二是本体论神经网络ONN，其损失函数包含三个结构项：L_consensus保证节点间共识，L_ricci通过Forman-Ricci曲率惩罚局部几何畸变，L_homology通过持久同调保持全局拓扑特征。在300万节点规模的测试中，系统实现了99.75%的拓扑保持率，相较于Transformer基线困惑度提升14.7%，相关工作已发布于arXiv编号2506.19277，并被Int. J. Topol. 2026接收。ORTSF算子族则在该拓扑之上以延迟鲁棒反馈闭合控制环路。",

      "吴在洪的研究实践揭示了一种深刻的双向对话关系：硬件的失败为理论提供数据，而理论的精进反过来指导硬件决策。当机械臂在控制边界附近产生振荡时，他意识到这不仅仅是PID参数调节问题，而是拓扑结构缺失的征兆——系统的吸引子在状态空间中并未形成完整的拓扑封闭结构。当摄像头在突发负载下出现帧同步失效时，他将其解读为时序假设违反，而非单纯的硬件故障，这促使他重新审视ONN中时序一致性约束的形式化方式。当机械臂在未见过的空间配置下抓取失败时，他将失败归因于关系几何的不完整性，这与SCC中支撑空间覆盖不足的形式化描述直接对应。反方向的影响同样具体：SCC中闭合项的稳定化倾向直接告知控制器设计，无需追求精确不动点收敛，只需保证系统轨迹落入有界吸引域即可，这一洞见简化了Frontier机械臂的控制策略。ONN中Betti数的持久性保持约束则告知传感器融合模块：重建结果必须在拓扑意义上忠实于真实场景，而非仅在欧氏距离意义上接近，这意味着深度传感器需要用拓扑一致性指标来验证，而不仅仅是点云精度。吴在洪将这种双向箭头视为他研究工作的核心方法论。他正在构建的是一个本体结构在每一层都明确维持的认知推理架构——从原始传感器输入，经过保持关系拓扑的学习潜在表征，直至驱动物理硬件的控制接口。值得解决的问题是那些正确把握拓扑会强制产生更好工程决策的问题，以及硬件反过来揭示理论空白的问题——正是在这个交叉点，他想工作。",

      "在工程实践与哲学追问之间，吴在洪一直在寻找一条将两者严格统一的道路。那个在工程学之前就已存在的问题——观察者与被观察对象之间的间隙，无法完整自我观察时何物得以留存——最终以最精确的形式落地为拓扑语言。SCC的凝聚场是当没有观察者拥有完整访问权时依然持存的东西，是场的规范不变性使得这种持存具有鲁棒性而非偶然性。A3公理下的稳定化倾向而非幂等性，是刻意选择的更弱主张——场趋向稳定构型却不必到达不动点，这种渐近行为更接近那些在不解决观察者-被观察对象间隙的情况下仍能运作的系统的真实状态。这一形式化不是哲学装饰，因为它对传感器规格、控制频率和规划器设计选择都有直接的下游工程推论。他正在构建的认知推理架构使本体结构在每一层都明确：从原始传感器输入，经过保留关系拓扑的学习潜在表征，到移动物理硬件的控制接口。在这条路径上，拓扑的正确性是承重的——错误会以具体、可诊断的方式使系统失效，而正确则会开启此前不可能的一类行为。两个方向的箭头同时流动的研究环境，是他持续工作的目标所在。",
    ],
  },
};
